"""
Sample Articles for Text Summarization
"""

sample_articles = {
    "Select a sample...": "",
    
    "About Dogs": """Dogs are wonderful pets and loyal companions. They provide unconditional love to their owners. Dogs need regular exercise and a healthy diet. Training your dog is important for good behavior. Dogs can learn many tricks and commands. They are very intelligent animals. Dogs have been humans' best friends for thousands of years. Taking care of a dog is a big responsibility.""",
    
    "About Internet": """The internet has changed how we communicate with each other. People can now send messages instantly across the world. Social media platforms connect billions of users globally. Online shopping has made buying products more convenient. Students can access educational resources from anywhere. However, internet addiction is becoming a serious problem. Many people spend too much time on their phones. Cybersecurity is also a major concern today. Hackers can steal personal information online. Despite the risks, the internet remains an essential tool. It has revolutionized business, education, and entertainment.""",
    
    "About Electric Vehicles": """Electric vehicles are becoming more popular every year. Major car manufacturers are investing heavily in electric technology. EVs produce zero direct emissions, making them environmentally friendly. The main advantage of electric cars is lower operating costs. Electricity is cheaper than gasoline in most countries. Electric motors require less maintenance than traditional engines. However, the initial purchase price is still high. Battery technology continues to improve rapidly. Modern EVs can travel over 300 miles on a single charge. Charging infrastructure is expanding in cities worldwide. Governments offer incentives to encourage EV adoption. Some people worry about charging time compared to refueling gas cars. Despite challenges, electric vehicles represent the future of transportation. Climate change concerns are driving the shift to electric mobility.""",
    
    "About Artificial Intelligence": """Artificial intelligence has revolutionized numerous industries in recent years. Machine learning algorithms now power everything from recommendation systems to autonomous vehicles. Deep learning, a subset of machine learning, uses neural networks with multiple layers to process complex patterns in data. Companies are investing billions in AI research and development. Natural language processing has enabled machines to understand and generate human language with remarkable accuracy. Computer vision systems can now identify objects and faces with superhuman precision. However, concerns about AI ethics and bias remain significant. Researchers are working on making AI systems more transparent and accountable. The future of AI promises even more transformative applications across healthcare, education, and scientific research.""",
    
    "About Space Exploration": """Space exploration has entered a new era of commercial involvement and international cooperation. Private companies are now launching satellites and carrying astronauts to the International Space Station. NASA's Artemis program aims to return humans to the Moon and establish a sustainable presence there. Mars remains a primary target for future human exploration missions. Robotic probes have discovered evidence of ancient water on Mars, raising questions about past life. The James Webb Space Telescope is revealing unprecedented details about distant galaxies and exoplanets. Scientists have identified thousands of planets orbiting other stars, some potentially habitable. Space tourism is becoming a reality, though currently accessible only to the wealthy."""
}